// import { Conscript } from "./types";

// export const conscripts: Conscript[] = [
//   {
//     id: 1,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Полномочия",
//     status: "Ожидает приема",
//   },
//   {
//     id: 2,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "На приеме",
//   },
//   {
//     id: 3,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "Завершено",
//   },
//   {
//     id: 4,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "На комиссии",
//   },
//   {
//     id: 5,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "На приеме",
//   },
//   {
//     id: 6,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "Результат готов",
//   },
//   {
//     id: 7,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "На приеме",
//   },
//   {
//     id: 8,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "На приеме",
//   },
//   {
//     id: 9,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "Ожидает приема",
//   },
//   {
//     id: 10,
//     name: "Фамилия Имя Отчество",
//     login: "login.kz.army",
//     militaryId: "Lorem Ipsum",
//     department: "Первичный",
//     status: "На приеме",
//   },
// ];
