import { AlertRow } from "./types";

export const alertRows: AlertRow[] = [
  {
    id: "1",
    name: "Kuanyshbayeava Zhanzhetpes Zhumabekuly",
    role: "Призывник",
    alert: "Истёкшие сертификаты безопасности",
    status: "Важно",
    checked: false,
  },
  {
    id: "2",
    name: "Jane Doe",
    role: "Доктор",
    alert: "Системные сбои",
    status: "В процессе",
    checked: false,
  },
  {
    id: "3",
    name: "Jane Doe",
    role: "Координатор",
    alert: "Системные сбои",
    status: "Устранено",
    checked: true,
  },
  {
    id: "4",
    name: "Jane Doe",
    role: "Призывник",
    alert: "Истёкшие сертификаты безопасности",
    status: "Важно",
    checked: false,
  },
  {
    id: "5",
    name: "Jane Doe",
    role: "Доктор",
    alert: "Системные сбои",
    status: "В процессе",
    checked: false,
  },
  {
    id: "6",
    name: "Jane Doe",
    role: "Координатор",
    alert: "Истёкшие сертификаты безопасности",
    status: "Устранено",
    checked: true,
  },
  {
    id: "7",
    name: "Jane Doe",
    role: "Доктор",
    alert: "Системные сбои",
    status: "В процессе",
    checked: false,
  },
  {
    id: "8",
    name: "Jane Doe",
    role: "Координатор",
    alert: "Системные сбои",
    status: "Устранено",
    checked: true,
  },
  {
    id: "9",
    name: "Jane Doe",
    role: "Призывник",
    alert: "Истёкшие сертификаты безопасности",
    status: "Важно",
    checked: false,
  },
  {
    id: "10",
    name: "Jane Doe",
    role: "Доктор",
    alert: "Системные сбои",
    status: "В процессе",
    checked: false,
  },
  {
    id: "11",
    name: "Jane Doe",
    role: "Координатор",
    alert: "Системные сбои",
    status: "Устранено",
    checked: true,
  },
  {
    id: "12",
    name: "Jane Doe",
    role: "Призывник",
    alert: "Истёкшие сертификаты безопасности",
    status: "Важно",
    checked: false,
  },
  {
    id: "13",
    name: "Jane Doe",
    role: "Доктор",
    alert: "Системные сбои",
    status: "В процессе",
    checked: false,
  },
  {
    id: "14",
    name: "Janeee Doe",
    role: "Координатор",
    alert: "Истёкшие сертификаты безопасности",
    status: "Устранено",
    checked: true,
  },
  {
    id: "15",
    name: "Jane Doe",
    role: "Доктор",
    alert: "Системные сбои",
    status: "В процессе",
    checked: false,
  },
  {
    id: "16",
    name: "Jane Doe",
    role: "Координатор",
    alert: "Системные сбои",
    status: "Устранено",
    checked: true,
  },
];
